### ISSUE TITLE
*** Assertion failure in + [NSView _findFirstKeyViewInDirection:forKeyLoopGroupingView:]

### ISSUE THREAD

**Issue by beckysippert** [sbooth/SFBPopovers#8]
This was also an issue in the [INPopoverController project.](https://github.com/indragiek/INPopoverController/issues/4)

According to that thread, this error sometimes arises when trying to enable keyboard access within a popover. It crashes the app on OS X 10.11 and previous. The only fix is to remove the contentView override accessor in SFBPopoverWindow.m.

I confirmed this fix in my project locally and can open a pull request for it as well.

**Comment by sbooth** [comment]
I verified PR #9 fixes this issue.

I'm less certain if there would be any unintended side effects of the change.  I think I'd prefer a fix where `contentView` was renamed to `popoverContentView` and is called explicitly.

**Comment by sbooth** [comment]
Fixed in 40b683d7527ba4249b32591cfe2be7f7d9105840

**Comment by joubin** [comment]
Has the pod been update to reflect this change? It looks like the pod is still 1.0.0 and I'm still having this issues. 

Thanks for the support

**Comment by joubin** [comment]
Hey, I was wondering if the pod will ever be updated to include this change.

**Comment by sbooth** [comment]
I updated the podspec to version 1.1.0
